#!/bin/bash

TEAM_ID=`cat team-id.albert.txt`

COMMAND=$1

if [[ "$COMMAND" == "list-repos" ]]; then
	./list-repos
elif [[ "$COMMAND" == "merge-ami-prs" ]]; then
	./merge-ami-prs
elif [[ "$COMMAND" == "replace-text" ]]; then
	./replace-text "$2" "$3" "$4" "$5"
elif [[ "$COMMAND" == "setup" ]]; then
	./setup "$2"
else
	echo "Nothing to do !"
fi

