#!/bin/bash

COMMAND=$1

if [[ "$COMMAND" == "list-repos" ]]; then
	./list-repos
elif [[ "$COMMAND" == "merge-ami-prs" ]]; then
	./merge-ami-prs
elif [[ "$COMMAND" == "replace-text" ]]; then
	./replace-text "$@"
elif [[ "$COMMAND" == "setup" ]]; then
	./setup "$@"
elif [[ "$COMMAND" == "set-team" ]]; then
	./set-team "$@"
elif [[ "$COMMAND" == "execute" ]]; then
	./execute "$@"
elif [[ "$COMMAND" == "clone-all-repos" ]]; then
	./clone-all-repos
else
	echo -e "Operation not recognised!\nValid operations:\nlist-repos\nmerge-ami-prs\nreplace-text\nsetup\nset-team\nexecute\nclone-all-repos"
	exit 1
fi
