#!/bin/bash

MY_DIR="$(dirname "$0")"
source "$MY_DIR/util"

check_access_token

REPO_NAMES=$(get_repos)

for REPO in $REPO_NAMES; do

    echo $REPO

    cd ~/git

    git clone git@github.com:Scout24/$REPO.git

done;
