#!/bin/bash

MY_DIR="$(dirname "$0")"
source "$MY_DIR/util"

check_access_token

COMMAND="$1"

REPO_NAMES=$(get_repos)

for REPO in $REPO_NAMES; do
	echo "$(tput bold)=====$REPO=====$(tput sgr0)"
	cd ~/git/$REPO
	if [ $? -ne 0 ]; then
		git clone git@github.com:Scout24/$REPO.git
		cd $REPO
	fi

    ${COMMAND//REPO/$REPO}

	cd ~/git

    continue
done;
