#!/bin/bash
USAGE="Lists all repos owned by the team\n"
USAGE+="Usage: albert list-repos"

([[ "$1" == "help" ]] || [[ "$2" == "help" ]] ) && { echo -e "$USAGE"; exit 0; }

MY_DIR="$(dirname "$0")"
source "$MY_DIR/util"

check_access_token

REPO_NAMES=$(get_repos)

echo $REPO_NAMES | tr " " "\n"

exit 0
