#!/bin/bash

MY_DIR="$(dirname "$0")"
source "$MY_DIR/util"

TEAM_ID=`cat team-id.albert.txt`

FILE="$1"
SEARCH_TEXT="$2"
NEW_TEXT="$3"
COMMIT_MSG="$4"

check_access_token

replace_text(){
    SEPARATOR="~"

    # Use another separator if input strings contain default separator
    if [[ "$SEARCH_TEXT$NEW_TEXT" = *"$SEPARATOR"* ]]; then
        echo "It's there!"
        SEPARATOR="%"
    fi

	gsed -i "s$SEPARATOR$SEARCH_TEXT$SEPARATOR$NEW_TEXT$SEPARATOR" $FILE
}

# filter out repos our team is not admin of; otherwise, e.g. security-configuration would appear in the list as of now (2017-12)
REPO_NAME_FILTER="map(select(.permissions.admin == true)) | map(.name) | .[]"

REPO_NAMES=`http GET "https://api.github.com/teams/$TEAM_ID/repos?per_page=100&access_token=$ACCESS_TOKEN" | jq -r "$REPO_NAME_FILTER" | sort`

for REPO in $REPO_NAMES; do
	echo "$(tput bold)=====$REPO=====$(tput sgr0)"
	cd ~/git/$REPO
	if [ $? -ne 0 ]; then
		git clone git@github.com:Scout24/$REPO.git
		cd $REPO
	fi


	if [ -f "$FILE" ]; then

        grep -q "$SEARCH_TEXT" "$FILE"
        if [ $? -eq 0 ]; then
			git stash
			git checkout master
			git pull

			replace_text

			git diff

			read -p "Should i commit and push changes? [y/n] " -n 1 -r
			echo

			if [[ $REPLY =~ ^[Yy]$ ]]; then
                git add -A
				git commit -m "$COMMIT_MSG"
				git push
			else
				git stash
                read -p "Should i open the original file with vim? [y/n] " -n 1 -r
			    echo

                if [[ $REPLY =~ ^[Yy]$ ]]; then
                    vim $FILE
                    git diff

                    read -p "Should i commit and push changes? [y/n]" -n 1 -r
			        echo

                    if [[ $REPLY =~ ^[Yy]$ ]]
                    then
                        git add -A
                        git commit -m "$COMMIT_MSG"
                        git push
                    else
                        git stash
                    fi
                else
                    git stash
                fi
			fi
        fi
	fi

	cd ~/git

    continue
done;


