#!/bin/bash
USAGE="Installs necessary tools, add some configuration to .bash_profile and sets up github team id which is needed for all operations.\n"
USAGE+="Usage: ./$(basename "$0") \"github team name\"\n"
USAGE+="Example: ./$(basename "$0") \"ConMon\""

[[ "$1" == "help" ]] && { echo -e "$USAGE"; exit 0; }
[[ $# != 1 ]] && { echo -e "$USAGE"; exit 1; }  # Show usage when argument count is wrong

brew install gnu-sed
brew install httpie
brew install jq

MY_DIR="$(dirname "$0")"
"$MY_DIR/set-team" "$1"

INPUT_VALID=false

until [ "$INPUT_VALID" = true ]
do
    read -p "Please enter root directory where you keep your git repos or where you want Albert to work in:"

    eval INPUT=$REPLY   # We do this to replace special characters like '~'

    if [[ "$INPUT" != "" ]] && [ -d $INPUT ]; then
        echo "$INPUT" > "$MY_DIR/root-dir.albert.txt"
        INPUT_VALID=true
    fi

    [ "$INPUT_VALID" = false ] && echo "Given path is invalid. Please try again."
done


# TODO: Refactor the duplications below to a util function
grep -q "alias albert" "$HOME/.bash_profile" 2> /dev/null
if [ $? -ne 0 ]; then
    printf "\nsource ~/git/albert/bash_completion\n" >> "$HOME/.bash_profile"
    printf "alias albert=\"~/git/albert/albert\"\n" >> "$HOME/.bash_profile"
fi

grep -q "alias albert" ~/.zshrc 2> /dev/null
if [ $? -ne 0 ]; then
    printf "\nsource ~/git/albert/bash_completion\n" >> "$HOME/.zshrc"
    printf "alias albert=\"~/git/albert/albert\"\n" >> "$HOME/.zshrc"
fi

grep -q "alias albert" ~/.bashrc 2> /dev/null
if [ $? -ne 0 ]; then
    printf "\nsource ~/git/albert/bash_completion\n" >> "$HOME/.bashrc"
    printf "alias albert=\"~/git/albert/albert\"\n" >> "$HOME/.bashrc"
fi

exit 0
